version: "3"
services:
  rank:
    container_name: rank
    build:
      context: .
    env_file:
      - ./.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
    ports:
      - "${RANKER_PORT}:${RANKER_PORT}"
      - "${RANKER_SUPERVISOR_PORT}:${RANKER_SUPERVISOR_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
      - ../:/home/murphy/robokop-rank