version: "3"
services:
  rank:
    # image: patrickkwang/robokop-rank
    build:
      context: .
    env_file:
      - ../../shared/robokop.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
      - NEO4J_HOST=neo4j
      - REDIS_HOST=redis
      - ROBOKOP_HOST=0.0.0.0
      - FLOWER_ADDRESS=0.0.0.0
      - SUPERVISOR_HOST=0.0.0.0
    ports:
      - "${RANKER_PORT}:${RANKER_PORT}"
      - "${FLOWER_PORT}:${FLOWER_PORT}"
      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    volumes:
      - ..:/home/murphy/robokop-rank
    # stdin_open: true
    # tty: true
    # command: bash
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default