apiVersion: v1
kind: Service
metadata:
  name: robokop-omnicorp
spec:
  selector:
    app: robokop-omnicorp
  type: NodePort
  ports:
    # ranker port
    - name: robokop-omnicorp-port
      protocol: TCP
      port: 5433
      targetPort: 5433