apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-omnicorp-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    hostPath:
      path: "/mnt/data/omnicorp"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-omnicorp-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-omnicorp-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: robokop-omnicorp-pv
kind: List